update build method to use Swift build

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -209,9 +209,9 @@ if [ -d $BUILD_DIR/PerfectLibraries -a -d $BUILD_DIR/webroot ]; then
   else
     fail Creating application directories
   fi
-cd $BUILD_DIR/src
-make > $BUILD_DIR/build.log 2>&1 || fail make
-make install > $BUILD_DIR/build.log 2>&1 || fail make install
+cd $BUILD_DIR/Sources
+swift build > $BUILD_DIR/build.log 2>&1 || fail swift build
+#make install > $BUILD_DIR/build.log 2>&1 || fail make install
 popd
 say Ok
 
