remove swift build instruction for testing

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -214,7 +214,7 @@ if [ -d $BUILD_DIR/PerfectLibraries -a -d $BUILD_DIR/webroot ]; then
     fail Creating application directories
   fi
 cd $BUILD_DIR/Sources
-swift build > $BUILD_DIR/build.log 2>&1 || fail swift build
+#swift build > $BUILD_DIR/build.log 2>&1 || fail swift build
 #make install > $BUILD_DIR/build.log 2>&1 || fail make install
 popd
 say Ok
